### ISSUE TITLE
gh-pages version and jekyll version problem

### ISSUE THREAD

**Issue by DarkHollow** [github/pages-gem#351]
I'm having a version problem when I do install or update. Instead of getting gh-pages 104 and jekyll 3.3.0, I'm getting 35/39 and 2.4.0

I do as follows

    $ jekyll new darkhollow.github.io

And get

    New jekyll site installed in /Users/roberto/Proyectos/darkhollow.github.io. 
    Running bundle install in /Users/roberto/Proyectos/darkhollow.github.io... 
    Fetching gem metadata from https://rubygems.org/...........
    Fetching version metadata from https://rubygems.org/..
    Fetching dependency metadata from https://rubygems.org/.
    Resolving dependencies...
    Using public_suffix 2.0.3
    Using colorator 1.1.0
    Using ffi 1.9.14
    Using forwardable-extended 2.6.0
    Using sass 3.4.22
    Using rb-fsevent 0.9.8
    Using kramdown 1.12.0
    Using liquid 3.0.6
    Using mercenary 0.3.6
    Using rouge 1.11.1
    Using safe_yaml 1.0.4
    Using minima 2.0.0
    Using bundler 1.13.6
    Using addressable 2.5.0
    Using rb-inotify 0.9.7
    Using pathutil 0.14.0
    Using jekyll-sass-converter 1.4.0
    Using listen 3.0.8
    Using jekyll-watch 1.5.0
    Using jekyll 3.3.0
    Using jekyll-feed 0.8.0
    Bundle complete! 3 Gemfile dependencies, 21 gems now installed.
    Use `bundle show [gemname]` to see where a bundled gem is installed.

And then

    $ cd darkhollow.github.io/
    $ vim Gemfile 

and I comment the line: `gem "jekyll", "3.3.0"`
and I uncomment the line: `gem "github-pages", group: :jekyll_plugins`

Finally I do

    $ bundle update

and I get this

    Fetching gem metadata from https://rubygems.org/..................
    Fetching version metadata from https://rubygems.org/...
    Fetching dependency metadata from https://rubygems.org/..
    Resolving dependencies...
    Using RedCloth 4.2.9
    Using concurrent-ruby 1.0.2
    Using i18n 0.7.0
    Using minitest 5.9.1
    Using thread_safe 0.3.5
    Using addressable 2.4.0 (was 2.5.0)
    Using blankslate 2.1.2.4
    Using fast-stemmer 1.0.2
    Using coffee-script-source 1.10.0
    Using execjs 2.7.0
    Using colorator 0.1 (was 1.1.0)
    Using ffi 1.9.14
    Using multipart-post 2.0.0
    Using gemoji 2.1.0
    Using net-dns 0.8.0
    Using public_suffix 1.5.3 (was 2.0.3)
    Using jekyll-paginate 1.1.0
    Using sass 3.4.22
    Using rb-fsevent 0.9.8
    Using kramdown 1.5.0 (was 1.12.0)
    Using liquid 2.6.2 (was 3.0.6)
    Using mercenary 0.3.6
    Using posix-spawn 0.3.12
    Using yajl-ruby 1.2.1
    Using redcarpet 3.1.2
    Using safe_yaml 1.0.4
    Using mini_portile2 2.1.0
    Using jekyll-sitemap 0.8.1
    Using maruku 0.7.0
    Using rdiscount 2.1.7
    Using unicode-display_width 1.1.1
    Using jekyll-feed 0.7.2 (was 0.8.0)
    Using minima 2.0.0
    Using bundler 1.13.6
    Using tzinfo 1.2.2
    Using parslet 1.5.0
    Using classifier-reborn 2.0.4
    Using coffee-script 2.4.1
    Using ethon 0.9.1
    Using rb-inotify 0.9.7
    Using faraday 0.9.2
    Using jekyll-sass-converter 1.2.0 (was 1.4.0)
    Using pygments.rb 0.6.1
    Using nokogiri 1.6.8.1
    Using terminal-table 1.7.3
    Using activesupport 5.0.0.1
    Using toml 0.1.2
    Using jekyll-coffeescript 1.0.1
    Using typhoeus 0.8.0
    Using listen 3.0.8
    Using sawyer 0.7.0
    Using html-pipeline 1.9.0
    Using github-pages-health-check 0.3.2
    Using jekyll-watch 1.5.0
    Using octokit 4.4.1
    Using jekyll-gist 1.4.0
    Using jekyll 2.4.0 (was 3.3.0)
    Using jekyll-mentions 0.2.1
    Using jekyll-redirect-from 0.6.2
    Using jemoji 0.4.0
    Using github-pages 35
    Bundle updated!

So `jekyll` goes back to `2.4.0` version and `github-pages` to `35` version.

If I delete the `Gemfile.lock` and do `bundle install` it gets the same versions.

And if I serve I get an error, I do

    $ bundle exec jekyll serve

and get

      Configuration file: /Users/roberto/Proyectos/darkhollow.github.io/_config.yml
                  Source: /Users/roberto/Proyectos/darkhollow.github.io
             Destination: /Users/roberto/Proyectos/darkhollow.github.io/_site
            Generating... 
           Build Warning: Layout 'post' requested in _posts/2016-11-05-welcome-to-jekyll.markdown does not exist.
        Liquid Exception: Included file '_includes/icon-github.html' not found in about.md
    jekyll 2.4.0 | Error:  Included file '_includes/icon-github.html' not found

I guess it's for the old versions I get when I do `update`

Last try, if I only write in the `Gemfile` source and the github pages gem, I get this versions
```$ bundle update
Fetching gem metadata from https://rubygems.org/...........
Fetching version metadata from https://rubygems.org/..
Fetching dependency metadata from https://rubygems.org/.
Resolving dependencies....
Using RedCloth 4.2.9
Using concurrent-ruby 1.0.2
Using i18n 0.7.0
Using minitest 5.9.1
Using thread_safe 0.3.5
Using addressable 2.4.0
Using blankslate 2.1.2.4
Using fast-stemmer 1.0.2
Using coffee-script-source 1.10.0
Using execjs 2.7.0
Using colorator 0.1
Using ffi 1.9.14
Using multipart-post 2.0.0
Using gemoji 2.1.0
Using net-dns 0.8.0
Using public_suffix 1.5.3
Using jekyll-paginate 1.1.0
Using sass 3.4.22
Using rb-fsevent 0.9.8
Using kramdown 1.5.0
Using liquid 2.6.2
Using mercenary 0.3.6
Using posix-spawn 0.3.12
Using yajl-ruby 1.2.1
Using redcarpet 3.3.2
Using safe_yaml 1.0.4
Using jekyll-feed 0.3.1
Using mini_portile2 2.1.0
Using jekyll-sitemap 0.8.1
Using maruku 0.7.0
Using rdiscount 2.1.7
Using unicode-display_width 1.1.1
Using bundler 1.13.6
Using tzinfo 1.2.2
Using parslet 1.5.0
Using classifier-reborn 2.0.4
Using coffee-script 2.4.1
Using ethon 0.9.1
Using rb-inotify 0.9.7
Using faraday 0.9.2
Using jekyll-sass-converter 1.3.0
Using pygments.rb 0.6.3
Using nokogiri 1.6.8.1
Using terminal-table 1.7.3
Using activesupport 5.0.0.1
Using toml 0.1.2
Using jekyll-coffeescript 1.0.1
Using typhoeus 0.8.0
Using listen 3.0.8
Using sawyer 0.7.0
Using html-pipeline 1.9.0
Using github-pages-health-check 0.3.2
Using jekyll-watch 1.5.0
Using octokit 4.4.1
Using jekyll-gist 1.4.0
Using jekyll 2.4.0
Using jekyll-mentions 0.2.1
Using jekyll-redirect-from 0.8.0
Using jemoji 0.5.0
Using github-pages 39
Bundle updated!

**Comment by csaid** [comment]
I believe I'm having the same issue. My Gemfile looks like this:
```
source 'https://rubygems.org'
gem 'github-pages', group: :jekyll_plugins
```
but when I `bundle update github-pages` it says "Using jekyll 2.4.0".

**Comment by bakercp** [comment]
Same issue here.

```
bakercp@skip:~/my-awesome-site$ github-pages versions
+---------------------------+---------+
| Gem                       | Version |
+---------------------------+---------+
| jekyll                    | 3.3.0   |
| jekyll-sass-converter     | 1.3.0   |
| kramdown                  | 1.11.1  |
| liquid                    | 3.0.6   |
| rouge                     | 1.11.1  |
| github-pages-health-check | 1.2.0   |
| jemoji                    | 0.7.0   |
| jekyll-mentions           | 1.2.0   |
| jekyll-redirect-from      | 0.11.0  |
| jekyll-sitemap            | 0.12.0  |
| jekyll-feed               | 0.8.0   |
| jekyll-gist               | 1.4.0   |
| jekyll-paginate           | 1.1.0   |
| jekyll-coffeescript       | 1.0.1   |
| jekyll-seo-tag            | 2.1.0   |
| jekyll-github-metadata    | 2.2.0   |
| jekyll-avatar             | 0.4.2   |
| listen                    | 3.0.6   |
| activesupport             | 4.2.7   |
| minima                    | 2.0.0   |
| jekyll-swiss              | 0.4.0   |
+---------------------------+---------+
```

bakercp@skip:~/my-awesome-site$ bundler exec github-pages versions
+-----------------------+---------+
| Gem                   | Version |
+-----------------------+---------+
| jekyll                | 2.4.0   |
| jekyll-coffeescript   | 1.0.1   |
| jekyll-sass-converter | 1.2.0   |
| kramdown              | 1.5.0   |
| maruku                | 0.7.0   |
| rdiscount             | 2.1.7   |
| redcarpet             | 3.1.2   |
| RedCloth              | 4.2.9   |
| liquid                | 2.6.2   |
| pygments.rb           | 0.6.1   |
| jemoji                | 0.4.0   |
| jekyll-mentions       | 0.2.1   |
| jekyll-redirect-from  | 0.6.2   |
| jekyll-sitemap        | 0.8.1   |
+-----------------------+---------+

```
bakercp@skip:~/my-awesome-site$ cat Gemfile
source "https://rubygems.org"
ruby RUBY_VERSION

# Hello! This is where you manage which Jekyll version is used to run.
# When you want to use a different version, change it below, save the
# file and run `bundle install`. Run Jekyll with `bundle exec`, like so:
#
#     bundle exec jekyll serve
#
# This will help ensure the proper Jekyll version is running.
# Happy Jekylling!
#gem "jekyll", "3.3.0"

# This is the default theme for new Jekyll sites. You may change this to anything you like.
gem "minima", "~> 2.0"

# If you want to use GitHub Pages, remove the "gem "jekyll"" above and
# uncomment the line below. To upgrade, run `bundle update github-pages`.
gem "github-pages", group: :jekyll_plugins

# If you have any plugins, put them here!
group :jekyll_plugins do
   gem "jekyll-feed", "~> 0.6"
end
```

```
bakercp@skip:~/my-awesome-site$ bundler update github-pages
Fetching gem metadata from https://rubygems.org/...........
Fetching version metadata from https://rubygems.org/..
Fetching dependency metadata from https://rubygems.org/.
Resolving dependencies...
Using RedCloth 4.2.9
Using concurrent-ruby 1.0.2
Using i18n 0.7.0
Using minitest 5.9.1
Using thread_safe 0.3.5
Using addressable 2.4.0
Using blankslate 2.1.2.4
Using fast-stemmer 1.0.2
Using coffee-script-source 1.10.0
Using execjs 2.7.0
Using colorator 0.1
Using ffi 1.9.14
Using multipart-post 2.0.0
Using gemoji 2.1.0
Using net-dns 0.8.0
Using public_suffix 1.5.3
Using jekyll-paginate 1.1.0
Using sass 3.4.22
Using rb-fsevent 0.9.8
Using kramdown 1.5.0
Using liquid 2.6.2
Using mercenary 0.3.6
Using posix-spawn 0.3.12
Using yajl-ruby 1.2.1
Using redcarpet 3.1.2
Using safe_yaml 1.0.4
Using mini_portile2 2.1.0
Using jekyll-sitemap 0.8.1
Using maruku 0.7.0
Using rdiscount 2.1.7
Using unicode-display_width 1.1.1
Using jekyll-feed 0.7.2
Using minima 2.0.0
Using bundler 1.13.6
Using tzinfo 1.2.2
Using parslet 1.5.0
Using classifier-reborn 2.0.4
Using coffee-script 2.4.1
Using ethon 0.9.1
Using rb-inotify 0.9.7
Using faraday 0.9.2
Using jekyll-sass-converter 1.2.0
Using pygments.rb 0.6.1
Using nokogiri 1.6.8.1
Using terminal-table 1.7.3
Using activesupport 5.0.0.1
Using toml 0.1.2
Using jekyll-coffeescript 1.0.1
Using typhoeus 0.8.0
Using listen 3.0.8
Using sawyer 0.7.0
Using html-pipeline 1.9.0
Using github-pages-health-check 0.3.2
Using jekyll-watch 1.5.0
Using octokit 4.4.1
Using jekyll-gist 1.4.0
Using jekyll 2.4.0
Using jekyll-mentions 0.2.1
Using jekyll-redirect-from 0.6.2
Using jemoji 0.4.0
Using github-pages 35
Bundle updated!
```

**Comment by h0r0man** [comment]
Same issue!

**Comment by DarkHollow** [comment]
I have found that in `Gemfile` if instead of

    gem "github-pages", group: :jekyll_plugins

I tell to use specific version

    gem "github-pages", "104"

apparently works fine if you `bundle update` or `bundle install` again, but of course, I don't think this is a fix.

**Comment by bakercp** [comment]
Thanks @DarkHollow I can confirm that when the contents of my `Gemfile` is 

```
source 'https://rubygems.org'
gem 'github-pages', '104', group: :jekyll_plugins
```

I am then able to run `bundle update` and then `bundle exec jekyll serve` and I'm back in action.

Thanks!

**Comment by nickmccurdy** [comment]
I also ran into this issue, including on Travis. It seems as if bundler is consistently installing the wrong version. Could it be that the version `39` is considered greater than `104` because they're being sorted alphabetically instead of numerically?

**Comment by sudopluto** [comment]
I am also having this issue.

**Comment by davidobrien1985** [comment]
I believe I'm seeing the same issue, although no idea how to fix it. I only really use Jekyll so that I can write markdown, don't really understand how Jekyll works.

I had a blog (www.david-obrien.net) that looked perfectly fine, pushed a new page, now it's broken. Reset the head to before I uploaded the commit, still broken.
This leads me to believe that something in the underlying Jekyll or Github infra is broken.

How do I fix or troubleshoot this?

**Comment by DarkHollow** [comment]
@davidobrien1985 have you did `bundle update` after modifying the `Gemfile`?

Anyway, I see your blog it's using SSL but I think GitHub Pages not, so the browser is trying to get the `css` and `js` from https://yourgithub.github.io/... but GitHub doesn't give the file over SSL.
<img width="761" alt="captura de pantalla 2016-11-06 a las 5 41 16" src="https://cloud.githubusercontent.com/assets/1090925/20035413/b6d33f26-a3e3-11e6-8b1d-fc2515bef284.png">

**Comment by nickmccurdy** [comment]
@davidobrien1985 Are you deploying this with GitHub Pages or a custom Jekyll based system? It sounds like you may want to try the Gemfile code in my comment (along with @DarkHollow's comment).

**Comment by davidobrien1985** [comment]
@DarkHollow I just realised, the Gemfile doesn't change the Github behaviour, right? That's just for local `jekyll serve` builds?
If the HTTPS thing is the issue then I don't know why now. This was always configured like this.

@nickmccurdy I'm using this with Github Pages.

**Comment by davidobrien1985** [comment]
Hmm, the `HTTPS` thing might have been it @DarkHollow .
I always had `url` in `_config.yml` commented out and it always worked, until now. Brought it back in with `https://www.david-obrien.net` and my formatting is correct again.
Thanks.

**Comment by nickmccurdy** [comment]
@davidobrien1985 As far as I'm aware, GitHub Pages runs something like `jekyll build --safe` with the same versions of Ruby, Jekyll, and plugins used in this gem. Having a Gemfile won't affect GitHub Page, you can't specify custom versions of gems.

**Comment by falsandtru** [comment]
I got the mostly same problem.

```
source 'https://rubygems.org'

gem 'travis'
gem 'github-pages'
```

or

```
source 'https://rubygems.org'

gem 'travis'
gem 'github-pages', group: :jekyll_plugins
```

```
$ bundle update
Fetching gem metadata from https://rubygems.org/.................
Fetching version metadata from https://rubygems.org/...
Fetching dependency metadata from https://rubygems.org/..
Resolving dependencies....................................................................
Using RedCloth 4.2.9
Using concurrent-ruby 1.0.2
Using i18n 0.7.0
Using minitest 5.9.1
Using thread_safe 0.3.5
Using addressable 2.4.0
Using backports 3.6.8
Using blankslate 2.1.2.4
Using fast-stemmer 1.0.2
Using coffee-script-source 1.10.0
Using execjs 2.7.0
Using colorator 0.1
Using connection_pool 2.2.0
Using ffi 1.9.14
Using multipart-post 2.0.0
Using gemoji 2.1.0
Using multi_json 1.12.1
Using net-http-pipeline 1.0.1
Using jekyll-paginate 1.1.0
Using sass 3.4.22
Using rb-fsevent 0.9.8
Using kramdown 1.3.1
Using liquid 2.6.1
Using mercenary 0.3.6
Using posix-spawn 0.3.12
Using yajl-ruby 1.1.0
Using redcarpet 3.1.2
Using safe_yaml 1.0.4
Using mini_portile2 2.1.0
Using jekyll-sitemap 0.6.0
Using maruku 0.7.0
Using rdiscount 2.1.7
Using highline 1.7.8
Using json 2.0.2
Using websocket 1.2.3
Using bundler 1.13.6
Using tzinfo 1.2.2
Using launchy 2.4.3
Using parslet 1.5.0
Using classifier-reborn 2.0.4
Using coffee-script 2.4.1
Using net-http-persistent 3.0.0
Using ethon 0.9.1
Using rb-inotify 0.9.7
Using faraday 0.9.2
Using jekyll-sass-converter 1.2.0
Using pygments.rb 0.6.0
Using nokogiri 1.6.8.1
Using pusher-client 0.6.2
Using activesupport 5.0.0.1
Using toml 0.1.2
Using jekyll-coffeescript 1.0.0
Using typhoeus 0.8.0
Using listen 3.0.8
Using faraday_middleware 0.10.0
Using gh 0.14.0
Using sawyer 0.7.0
Using html-pipeline 1.9.0
Using jekyll-watch 1.5.0
Using travis 1.8.2
Using octokit 4.4.1
Using jekyll-gist 1.4.0
Using jekyll 2.4.0
Using jekyll-mentions 0.1.3
Using jekyll-redirect-from 0.6.2
Using jemoji 0.3.0
Using github-pages 28
Bundle updated!
```

**Comment by DarkHollow** [comment]
@falsandtru 
Expecify the Github pages gem version

```ruby
source 'https://rubygems.org'
gem 'github-pages', '>=104', group: :jekyll_plugins
```
Use this as a temporary workaround.

**Comment by falsandtru** [comment]
I found the expected issue https://github.com/bundler/bundler/issues/5154. This is almost certainly a bug of bundler. A workaround is:

```
source 'https://rubygems.org'

gem 'github-pages'
```

```
$ gem uninstall bundler
$ gem install bundler -v 1.12.6
$ bundle update
Fetching gem metadata from https://rubygems.org/
Fetching version metadata from https://rubygems.org/
Fetching dependency metadata from https://rubygems.org/
Resolving dependencies.....................................................................................................................
Using i18n 0.7.0
Using json 1.8.3
Using minitest 5.9.1
Using thread_safe 0.3.5
Using addressable 2.4.0
Using coffee-script-source 1.10.0
Using execjs 2.7.0
Using colorator 1.1.0
Using ffi 1.9.14
Using multipart-post 2.0.0
Using forwardable-extended 2.6.0
Using gemoji 2.1.0
Using net-dns 0.8.0
Using public_suffix 1.5.3
Using sass 3.4.22
Using rb-fsevent 0.9.8
Using kramdown 1.11.1
Using liquid 3.0.6
Using mercenary 0.3.6
Using rouge 1.11.1
Using safe_yaml 1.0.4
Using jekyll-feed 0.7.2
Using mini_portile2 2.1.0
Using jekyll-paginate 1.1.0
Using jekyll-swiss 0.4.0
Using minima 2.0.0 (was 1.2.0)
Using unicode-display_width 1.1.1
Using bundler 1.12.6
Using tzinfo 1.2.2
Using jekyll-sitemap 0.11.0
Using coffee-script 2.4.1
Using ethon 0.9.1
Using rb-inotify 0.9.7
Using faraday 0.9.2
Using pathutil 0.14.0
Using jekyll-sass-converter 1.3.0
Using nokogiri 1.6.8.1
Using terminal-table 1.7.3
Using activesupport 4.2.7
Using jekyll-coffeescript 1.0.1
Using typhoeus 0.8.0
Using listen 3.0.6
Using sawyer 0.7.0
Using html-pipeline 2.4.2
Using jekyll-watch 1.5.0
Using octokit 4.4.1
Using jekyll 3.3.0 (was 3.2.1)
Using github-pages-health-check 1.2.0
Using jekyll-gist 1.4.0
Using jekyll-github-metadata 2.2.0 (was 2.1.1)
Using jekyll-mentions 1.2.0
Using jekyll-redirect-from 0.11.0
Using jekyll-seo-tag 2.0.0
Using jemoji 0.7.0
Using github-pages 102 (was 100)
Bundle updated!
```

**Comment by DarkHollow** [comment]
@falsandtru so if it's a bundler version issue I guess I'm going to close this issue.

**Comment by falsandtru** [comment]
I agree, we should go to that issue.

**Comment by jarrodwb** [comment]
Same issue. :+1:

**Comment by benbalter** [comment]
This is related to https://github.com/bundler/bundler/issues/5154. For now you can use the following work around which @nickmccurdy pointed out:

```ruby
source 'https://rubygems.org'
gem 'github-pages', '>=104', group: :jekyll_plugins
```

**Comment by nickmccurdy** [comment]
Related PR: https://github.com/CocoaPods/Molinillo/pull/54

**Comment by nickmccurdy** [comment]
This has been fixed upstream! Users of this gem should be fine now, though you might need to `bundle update`.

**Comment by DirtyF** [comment]
@nickmccurdy Not yet as the issue is still present as even if [the fix](https://github.com/bundler/bundler/commit/fa2fd9bee9f7075d45aa105378391abe0d83b6e9) has been merged into master, we still need to wait for next bundler gem release.

**Comment by falsandtru** [comment]
Now I can install the latest gh-pages gem via `bundle update` with bundler 1.13.6. However, I need to run that command two times.

**Comment by nickmccurdy** [comment]
Sweet, this now works for me on a clean `bundle install` (after deleting `Gemfile.lock`)!

**Comment by benbalter** [comment]
Based on @nickmccurdy and @falsandtru comments, I'm going to call this closed. Please follow their instructions if you are experiencing this issue.

**Comment by DarkHollow** [comment]
Alright, with the new version of `bundler` everything is going normally.

Thank you all for your help and dedication.

Closed.

**Comment by nickmccurdy** [comment]
This is back, bundler 1.16.1 is installing github-pages 39 again, even after wiping Gemfile.lock with `bundle install` or `bundle update`.

**Comment by AlistairB** [comment]
@nickmccurdy Seems that `html-proffer` `3.8.0` bumped a lot of gems while `github-pages` has older versions.

```
Bundler could not find compatible versions for gem "activesupport":
  In Gemfile:
    github-pages (>= 176) was resolved to 176, which depends on
      activesupport (= 4.2.9)

    html-proofer (>= 3.8.0) was resolved to 3.8.0, which depends on
      activesupport (< 6.0, >= 4.2)

Bundler could not find compatible versions for gem "typhoeus":
  In Gemfile:
    github-pages (>= 176) was resolved to 176, which depends on
      github-pages-health-check (= 1.3.5) was resolved to 1.3.5, which depends on
        typhoeus (~> 0.7)

    html-proofer (>= 3.8.0) was resolved to 3.8.0, which depends on
      typhoeus (~> 1.3)
```

Seems like the following is a reasonable temporary solution.

```
gem 'github-pages', group: :jekyll_plugins
gem 'html-proofer', '~> 3.7.0'
```

**Comment by NathanConroy** [comment]
I'm getting a varient of this issue. As at the top of this thread it's with the `github-pages` gem.

```
Blog nconroy$ bundle update
The dependency tzinfo-data (>= 0) will be unused by any of the platforms Bundler is installing for. Bundler is installing for ruby but the dependency is only for x86-mingw32, x86-mswin32, x64-mingw32, java. To add those platforms to the bundle, run `bundle lock --add-platform x86-mingw32 x86-mswin32 x64-mingw32 java`.
Fetching gem metadata from https://rubygems.org/..........
Fetching gem metadata from https://rubygems.org/.
Resolving dependencies...
Bundler could not find compatible versions for gem "jekyll":
  In Gemfile:
    github-pages was resolved to 4, which depends on
      jekyll (= 1.1.2)

    jekyll-feed (~> 0.6) was resolved to 0.9.3, which depends on
      jekyll (~> 3.3)
```

**Comment by cnizzardini** [comment]
I am getting a similar error as well

```
> bundle update
The dependency tzinfo-data (>= 0) will be unused by any of the platforms Bundler is installing for. Bundler is installing for ruby but the dependency is only for x86-mingw32, x86-mswin32, x64-mingw32, java. To add those platforms to the bundle, run `bundle lock --add-platform x86-mingw32 x86-mswin32 x64-mingw32 java`.
Fetching gem metadata from https://rubygems.org/..........
Fetching gem metadata from https://rubygems.org/.
Resolving dependencies...
Bundler could not find compatible versions for gem "jekyll":
  In Gemfile:
    github-pages was resolved to 4, which depends on
      jekyll (= 1.1.2)

    minima (~> 2.0) was resolved to 2.4.0, which depends on
      jekyll (~> 3.5)
```

To resolve this for now I altered my Jekyll version to 3.6.2 in my Gemfile and then specified: 

```
gem "github-pages", 179, group: :jekyll_plugins
```

Having never used Jekyll or done much with Ruby Gems I just kept bumping that number up till it matched. Weird stuff.

In any case this seems like a pretty poor work around....

**Comment by bingtanghulu** [comment]
bnm
